### PR TITLE
- added entities package and search/sort packages

### PR DESCRIPTION
**Pull request by Hclover2003**
- added entities package
- added search & sort packages (with files)

### CODE REVIEW

**Review by jkahn506 — APPROVED** [review]
You probably shouldn't have deleted the test file.

**Review by Brenden-Yiping-Wang — APPROVED** [review]
All changes are necessary!

**Review by YadingF — APPROVED** [review]
OK

**Review by Allisonc369 — APPROVED** [review]
All is good!

**Pull request merged**
