### PR TITLE
Changed a error in ProfileController

### PR DESCRIPTION
**Pull request by Allisonc369**
Last time, I accidentally wrote codes in main branch. So codes related to Profile were merged automatically in the main, but all other parts are not affected. Sorry for my mistake. There was minor error in my controller. This pull request has corrected the error.

### CODE REVIEW

**Review by jkahn506 — APPROVED** [review]
Ah no worries about the mistake!

**Review by Brenden-Yiping-Wang — APPROVED** [review]
Thanks for fixing the error

**Review by YadingF — APPROVED** [review]
ok

**Review by jkahn506 — APPROVED** [review]
Looks good

**Review by Brenden-Yiping-Wang — APPROVED** [review]
good

**Pull request merged**
