### PR TITLE
2 feature 2 search for recipe

### PR DESCRIPTION
**Pull request by Hclover2003**
- Implement strategy design pattern for sort. Created interface RecipeSorter and three classes that implement it based on the three different ways to sort (by average rating, number of reviews, and time needed)
- Created UI for inputting search/sort criteria, and for displaying results (no mains, can't run yet)
- Merged search/sort into one use case instead of two for simplicity
- Added test cases
- Added javadoc and comments for code readability
- Checked that it adheres to clean architecture and SOLID principles

### CODE REVIEW

**Review by YadingF — DISMISSED** [review]
ok

**Review by jkahn506 — DISMISSED** [review]
Looks good

**Review by Brenden-Yiping-Wang — DISMISSED** [review]
Good! We can interact with the ranking now.

**Review by jkahn506 — APPROVED** [review]

**Review by YadingF — APPROVED** [review]

**Review by Brenden-Yiping-Wang — APPROVED** [review]
Good. Now we can interact with the ranking

**Pull request merged**
