### PR TITLE
35 mealplan

### PR DESCRIPTION
**Pull request by luciatan**

### CODE REVIEW

**Review by YadingF — APPROVED** [review]
ok

**Review by jkahn506 — DISMISSED** [review]

**Review by Brenden-Yiping-Wang — DISMISSED** [review]
This change makes the Calories calculation function works, great!

**Review by jkahn506 — APPROVED** [review]
Looks good

**Review by Hclover2003 — APPROVED** [review]
looks good

**Review by Brenden-Yiping-Wang — APPROVED** [review]
Good

**Pull request merged**
