### PR TITLE
Changed Profile UI related files.

### PR DESCRIPTION
**Pull request by Allisonc369**

### CODE REVIEW

**Review by ika-joshi — DISMISSED** [review]

**Review by luciatan — APPROVED** [review]

**Review by Brenden-Yiping-Wang — DISMISSED** [review]
Good

**Review by Hclover2003 — APPROVED** [review]

**Review by jkahn506 — DISMISSED** [review]
Looks good

**Review by YadingF — DISMISSED** [review]
ok

**Review by jkahn506 — APPROVED** [review]
Looks good!

**Review by Brenden-Yiping-Wang — APPROVED** [review]
good

**Review by Brenden-Yiping-Wang — APPROVED** [review]
good

**Review by YadingF — DISMISSED** [review]
ok

**Review by Brenden-Yiping-Wang — APPROVED** [review]

**Review by ika-joshi — APPROVED** [review]

**Pull request merged**
