### PR TITLE
83 review and recipe removed

### PR DESCRIPTION
**Pull request by jkahn506**
So, I removed the uppercase Entity directory from main, but doing this deleted recipe.java and review.java, since they had been moved to the uppercase directory, not copied. This pull request adds them back. Sorry for the trouble!

### CODE REVIEW

**Review by YadingF — APPROVED** [review]
ok

**Review by Hclover2003 — APPROVED** [review]
sounds good, no problem :)

**Review by ika-joshi — APPROVED** [review]
sounds good!

**Review by Brenden-Yiping-Wang — APPROVED** [review]
Thank you for adding it back!

**Pull request merged**
